language: node_js

node_js:
  - "12"
  - "node"

os:
  - linux

sudo: false

cache:
    npm: false
    directories:
        - $HOME/.npm

env:
  global:
    - CC_TEST_REPORTER_ID=0a4da081e3fad94ed05f9d6cb75ec4e5bad81340097e0bc6a6f159b0a64f68bc
#### Rest of code omitted for clarity ####
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
#### Rest of code omitted for clarity ####
after_script:
#### - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
####  - ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.backend.json coverage/backend/.resultset.json 
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 2
